### ISSUE TITLE
Add support for both AND,OR logical operators.

### ISSUE THREAD

**Issue by cyilcode** [oplog/DynamicQueryBuilder#29]
Currently DQB can only execute `And` logical operator.

It should be supporting both `And` and `Or` logical operators.

Introduction of this enhancement should provide full functionality both on expression building and http query parsing sides.

**Comment by wensaint** [comment]
any thing new on this issue?

**Comment by wensaint** [comment]
anything new on this issue?

**Comment by SYOM29** [comment]
Should be resolved with c26e1985ab424bbbe9524412cf9be42105b97cbc.
