### ISSUE TITLE
Cannot create query with email

### ISSUE THREAD

**Issue by selmansener** [oplog/DynamicQueryBuilder#33]
When i tried to query Customers with this query;

`o=Equals&p=email&v=selman.sener@oplog.com.tr&s=createdAt,desc&offset=0&count=25`

 dqb throws this exception;

 `System.ArgumentException: Argument types do not match`

i realize that postman encodes query params;
`o%3DEquals%26p%3Demail%26v%3Dselman.sener%40oplog.com.tr%26s%3DcreatedAt%2Cdesc%26offset%3D0%26count%3D25`

than i tried to encode points as well, but result was same;

`o%3DEquals%26p%3Demail%26v%3Dselman%2Esener%40oplog%2Ecom%2Etr%26s%3DcreatedAt%2Cdesc%26offset%3D0%26count%3D25`

 `System.ArgumentException: Argument types do not match`

**Comment by cyilcode** [comment]
I am closing this issue since it wasn't actually a DQB related error.
